name: Security CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-docker-containers:
    uses: ./.github/workflows/build-docker-images-for-testing.yml
    secrets: inherit
    with:
      platform: linux/amd64

  test-rest-framework:
    needs: build-docker-containers
    uses: ./.github/workflows/rest-framework-tests.yml
    secrets: inherit
    with:
      platform: linux/amd64
      v3_feature_locations: false
